#! /bin/sh

xsetroot -cursor_name left_ptr
wmname LG3D

dunst &

# source the colors.
wal -R
. "${HOME}/.cache/wal/colors.sh"

# polybar
$HOME/.config/polybar/launch.sh &

# Set the border colors.
bspc config normal_border_color "$color0"
bspc config active_border_color "$color0"
bspc config focused_border_color "$color1"
bspc config presel_feedback_color "$color1"

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1 
bspc config window_gap           5 

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
