#!/bin/sh

case $BUTTON in
	1) notify-send "This Month" "$(cal --color=always | sed "s/..7m/<b><span color=\"red\">/;s/..27m/<\/span><\/b>/")" ;;
	3) setsid -f "$TERMINAL" -e calcurse ;;
esac

date "+^C7^%b %d (%a) ^C15^ ^C7^%I:%M%p "
